version: '3.9'
services:
  postgres:
    image: postgres:15-alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todoapi
    ports:
      - 5432:5432
    volumes:
      - dev-db-data:/var/lib/postgresql/data/

volumes:
  dev-db-data: