version: '3.9'
services:
  db:
    image: postgres:15-alpine3.18
    restart: always
    container_name: integration-tests-prisma
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tests
    volumes:
      - test-db-data:/var/lib/postgresql/data/
volumes:
  test-db-data:
